config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5) }
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = params[:query].present? ? Cocktail.where("lower(name) LIKE ?", "%#{params[:query].downcase}%") : Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail: @cocktail)
    @dose = Dose.new
    @reviews = Review.where(cocktail: @cocktail)
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(strong_params)

    if @cocktail.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def strong_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(strong_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @doses = Dose.where(cocktail: @cocktail)
      render 'cocktails/show'
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    dose.destroy
    @doses = Dose.where(cocktail: dose.cocktail)
    redirect_to cocktail_path(dose.cocktail)
  end

  private

  def strong_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @reviews = Review.where(cocktail: @cocktail)
    @review = Review.new(strong_params)
    @review.cocktail = @cocktail

    if @review.save
      sum = 0
      @reviews.each do |r|
        sum += r.rating
      end
      @cocktail.rating = sum.fdiv(@reviews.length).round
      @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      @reviews = Review.where(cocktail: @cocktail)
      render 'cocktails/show'
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    @reviews = Review.where(cocktail: review.cocktail)
    redirect_to cocktail_path(review.cocktail)
  end

  private

  def strong_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container my-3">
  <div class="cards">
    <% @cocktails.each do |cocktail| %>
      <%= link_to cocktail_path(cocktail) do %>
        <div class="card border-dark" style="width: 18rem;">
          <%= cl_image_tag cocktail.photo.key, height: 300, width: 300, crop: :fill, class: "card-img-top"  %>
          <div class="card-body bg-dark">
            <h5 class="card-title"><%= cocktail.name %></h5>
            <% if cocktail.rating.nil? %>
              <% 5.times do %>
                <i class="far fa-star"></i>
              <% end %>
            <% else %>
              <% cocktail.rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
              <% (5 - cocktail.rating).times do %>
                <i class="far fa-star"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container form">
  <h2 class="m-3">Add a new cocktail</h2>
  <div class="info-card p-3 m-3">
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.file_field :photo, as: :file %>
      <%= f.button :submit, class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container d-flex align-items-center my-3">
  <% if @cocktail.photo.attached? %>
    <%= cl_image_tag @cocktail.photo.key, height: 200, width: 200, crop: :fill, class: 'rounded-circle' %>
  <% end %>
  <h1 class="pl-5"><%= @cocktail.name %></h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-sm-12">
      <div class="info-card p-3 my-3">
        <h4>Make your own</h4>
        <ul>
          <% @doses.each do |dose| %>
            <li>
              <%= dose.ingredient.name %>, <%= dose.description %>
              <%= link_to dose_path(dose), method: :delete do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-lg-4 col-sm-12">
      <div class="info-card p-3 my-3">
        <h5>Add a new dose</h5>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.input :description %>
          <%= f.association :ingredient %>
          <%= f.button :submit, class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-sm-12">
      <div class="info-card p-3 my-3">
        <h4>What others say...</h4>
        <ul>
          <% @reviews.each do |review| %>
            <li>
              <% review.rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
              - <%= review.content %>
              <%= link_to review_path(review), method: :delete do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </li>
          <% end %>
        </ul>
        </div>
      </div>
    <div class="col-lg-4 col-sm-12">
      <div class="info-card p-3 my-3">
        <h5>Add a new review</h5>
        <%= simple_form_for [@cocktail, @review] do |f| %>
          <%= f.input :rating %>
          <%= f.input :content %>
          <%= f.button :submit, class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'shared/navbar.html.erb' %>
    <%= yield %>
    <%= render 'shared/footer.html.erb' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="container-fluid">
  <h5>Rain or shine <i class="fas fa-cloud-sun-rain fa-lg"></i> by Felicia G</h5>
  <div class="flex">
    <i class="fab fa-github fa-lg"></i>
    <i class="fab fa-twitter fa-lg"></i>
    <i class="fas fa-envelope fa-lg"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-cocktail"></i> Lift your spirits
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" value="<%= params[:query] %>">
      <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">
    </form>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Add cocktail', new_cocktail_path, class: "btn btn-outline-success ml-3" %>
      </li>
    </ul>
  </div>
</div>